---
title: "Install Prerequisite Tools"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Installation}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

## Install LTRpred and prerequisite R packages

__Note: please be aware that LTRpred is designed for Linux and unix based systems such as macOS. Hence, although LTRpred itself can be installed on Windows machines, most of the command line tools LTRpred depends on cannot be installed on Windows machines.__

Please make sure that [Bioconductor](https://www.bioconductor.org/install/) and all package dependencies are installed on the
system on which you would like to run `LTRpred`.

```r
# install Bioconductor
## try https:// if http:// URLs are not supported
source("http://bioconductor.org/biocLite.R")
biocLite()
```

Then install prerequisite Bioconductor packages:

```r
biocLite(c("GenomicFeatures","IRanges", "AnnotationDbi", "Biostrings"))
```

Now users may install `LTRpred` as follows:

```r
source("http://bioconductor.org/biocLite.R")
biocLite("devtools")
biocLite("HajkD/LTRpred")
```



## Install prerequisite command line tools

For the `LTRpred::LTRpred()` function to run properly, please make sure that the following command line tools are installed on your system:

## Install [GenomeTools](https://github.com/genometools/genometools)

For linux systems:

```bash
wget http://genometools.org/pub/genometools-1.5.7.tar.gz
tar -xf genometools-1.5.7.tar.gz
cd genometools-1.5.7
make with-hmmer=yes cairo=no 
make cairo=no test
make cairo=no install
```

For macOS systems:

```bash
# Go to: http://brew.sh/
# Install Homebrew: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

$ brew install caskroom/cask/brew-cask
$ brew cask install xquartz
$ brew install cairo
$ brew install pango
```

```bash
# install genometools
# download from http://genometools.org/pub/genometools-1.5.7.tar.gz
tar -xf genometools-1.5.7.tar.gz
cd genometools-1.5.7
make with-hmmer=yes cairo=no 
make cairo=no test
make cairo=no install
```

## Install [HMMER](http://hmmer.org/download.html)

For unix systems:

```bash
wget ftp://selab.janelia.org/pub/software/hmmer3/3.1b2/hmmer-3.1b2.tar.gz
tar xf hmmer-3.1b2.tar.gz
cd hmmer-3.1b2
 ./configure
 make
 make check
 sudo make install
```

## Install [USEARCH](http://drive5.com/usearch/download.html)

Example for macOS (analogous for linux systems):

```bash
# register and download operating system specific usearch from
# http://drive5.com/usearch/download.html
chmod +x usearch10.0.240_i86osx32
sudo cp usearch10.0.240_i86osx32 /usr/local/bin/
sudo mv /usr/local/bin/usearch10.0.240_i86osx32 /usr/local/bin/usearch
```

## Install [VSEARCH](https://github.com/torognes/vsearch)

Example for unix systems:

```bash
sudo git clone https://github.com/torognes/vsearch.git
cd vsearch
sudo ./configure
sudo make
sudo make install
```

## [BLAST](https://www.ncbi.nlm.nih.gov/books/NBK279671/)

For example for Linux systems open the Terminal application and run:

```bash
# download BLAST+ version 2.2.31
wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.31/ncbi-blast-2.2.31+-x64-linux.tar.gz

# extract the compiled version of BLAST
tar zxvpf ncbi-blast+2.2.31+-x64-linux.tar.gz

# copy BLAST files to `usr/local/bin`
cp ncbi-blast-2.2.31+/bin/* usr/local/bin
```

Alternatively users can set the system call to the BLAST programs by specifying the PATH variable (this is useful, because it allows an easier update of BLAST versions instead of deleting all BLAST programs from usr/local/bin):

```bash
# open vim text editor
vi .bash_profile

# type 'Shift' then I to edit the file .bash_profile
# and specify the export PATH
export PATH=${PATH}:/path/to/downloaded/blast/folder/ncbi-blast-2.2.31+/bin

# type 'ESC' then ':' then 'w' then 'q' to save and quit the .bash_profile file 
# log out from your server with
exit

# log in again and type
blastp -version
```

Now users should see the BLAST command line options.


### Install [Perl](https://www.perl.org/)

Please follow the instructions at https://learn.perl.org/installing/.

After installation, you should be able to execute the following command on the terminal:

```bash
perl -v
```

```
This is perl 5, version 18, subversion 2 (v5.18.2) built for darwin-thread-multi-2level
(with 2 registered patches, see perl -V for more detail)

Copyright 1987-2013, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

### Install [dfamscan.pl](http://www.dfam.org/web_download/Current_Release/dfamscan.pl)

[dfamscan.pl](http://www.dfam.org/web_download/Current_Release/dfamscan.pl) needs to be stored at `/usr/local/bin/dfamscan.pl` and executabe via `perl /usr/local/bin/dfamscan.pl -help`. This is important to be able to run the hmmer search against the Dfam database.





