#' @title Apply functions to meta data generated by \code{LTRpred}
#' @description Apply any function to the results generated by meta analyses
#' @param result.folder \code{result.folder} generated by \code{\link{LTRpred.meta}}.
#' @param FUN function to apply to meta data returned by \code{\link{LTRpred.meta}}.
#' @author Hajk-Georg Drost
#' @details 
#' This function
#' @examples 
#' \dontrun{
#' 
#' }
#' @seealso \code{\link{LTRpred.meta}}, \code{\link{LTRpred}}
#' @export
meta.apply <- function(result.folder,FUN){
  
  func <- match.fun(FUN)
  result.files <- list.files(result.folder)
  folders <- result.files[stringr::str_detect(result.files,"ltrpred")]
  
  for (i in 1:length(folders)){
    #currentFolder <- list.files(file.path(result.folder,folders[i]))
    LTRdigestFolder <- currentFolder[stringr::str_detect(currentFolder,"ltrdigest")]
    choppedFolder <- unlist(stringr::str_split(LTRdigestFolder,"_"))
    
    pred <- read.prediction(gff.file = file.path(result.folder,folders[i],paste0(paste0(choppedFolder[-length(choppedFolder)], collapse = "_"),"LTRdigest")))
    
    
  }
  
}