#' @title Genome size vs. LTR transposon content
#' @description Compute and visualize the correlation between genome size vs. LTR transposon content.
#' @param genome.summary a list generated by \code{\link{quality.filter.meta}} storing the \code{sim_file} and \code{gm_file} data.frames.
#' @param type type of LTR abundance. Options are: \code{type = "mass"} (total length of all TEs in Mbp), \code{type = "prop.mass"} (proportion of TEs within entire genome in %),
#' \code{type = "count"} (total number of TEs in genome), \code{type = "norm.count"} (total number of TEs in genome normalized by genome size in Mbp).
#' @param cor.method correlation analysis method. Either \code{"pearson"}, \code{"kendall"}, or \code{"spearman"}.
#' @param label.organism shall organism names be drawn in the figure?
#' @param smooth.method method to add a smoothed conditional mean (see \code{ggplot2::geom_smooth()}).
#' Users can choose from \code{auto}, \code{glm}, \code{lm}, or \code{loess}. If no smoothing function shall be applied,
#' users can specify \code{smooth.method = 'NULL'}.
#' @param se shall standard error of the smoothing model (grey area) be drawn or not. 
#' @param xlab x-axis label.
#' @param ylab y-axis label.
#' @param main main text.
#' @param alpha transparency of confidence interval of the smoothing function: between \[ 0,1 \].
#' @param arrow_lab whether or not data points shall be labelled with arrows (ggrepel). 
#' @param text.size size of the labels in ggplot2 notation.
#' @param label.size size of the dot-labels.
#' @param check.overlap shall overlaps of labels be avoided or not.
#' @author Hajk-Georg Drost
#' @details 
#' In the first step, users should have generated LTR retrotransposon annotations for several species using the
#' \code{\link[LTRpred]{LTRpred.meta}} function. The output of \code{\link[LTRpred]{LTRpred.meta}} is a folder storing the annotation files
#' for all species of input species. In addition, \code{\link[LTRpred]{LTRpred.meta}} generates two files: \code{*_SimilarityMatrix} and \code{*_GenomeInfo} .
#' @examples 
#' GenomeMatrix <- read.csv(system.file("GenomeMatrix.csv",package = "LTRpred"), sep = ";")
#' GenomeMatrix[ , 1] <- sapply(GenomeMatrix[ , 1], 
#'                              function(x) unlist(stringr::str_split(x,"_"))[1])
#'                              
#' plotSize(GenomeMatrix)
#' @export

plotSize <- function(genome.summary,
                     type                = "total_ltrs_nucl_mbp",
                     cor.method          = "spearman",
                     label.organism      = TRUE,
                     colour              = "black",
                     smooth.method       = "glm",
                     se                  = TRUE,
                     xlab                = "LTR retrotransposon content in Mega [bp]",
                     ylab                = "Genome size in Mega [bp]",
                     main                = "",
                     alpha               = 0.3,
                     arrow_lab           = FALSE,
                     text.size           = 18,
                     label.size          = 3,
                     check.overlap       = TRUE) {
    
    if (!is.element(type, c("total_ltrs_nucl_mbp", "n_ltrs_freq", "n_ltrs", "total_ltrs_nucl_freq")))
        stop("Please specify: type = 'total_ltrs_nucl_mbp' for total length of all TEs in Mbp; type = 'total_ltrs_nucl_freq' for proportion of TEs within entire genome in %; type = 'n_ltrs' for total number of TEs in genome; type = 'n_ltrs_freq' for total number of TEs in genome normalized by genome size in Mbp.", call. = FALSE)
    
        if (type == "n_ltrs")
        cor.value <-
            stats::cor(genome.summary$gm_file$n_ltrs, genome.summary$gm_file$genome_size_nucl_mbp, method = cor.method)
       
         if (type == "n_ltrs_freq")
            cor.value <-
            stats::cor(genome.summary$gm_file$n_ltrs_freq, genome.summary$gm_file$genome_size_nucl_mbp, method = cor.method)
        
        if (type == "total_ltrs_nucl_mbp")
            cor.value <-
            stats::cor(genome.summary$gm_file$total_ltrs_nucl_mbp, genome.summary$gm_file$genome_size_nucl_mbp, method = cor.method)
        
        if (type == "total_ltrs_nucl_freq")
            cor.value <-
            stats::cor(genome.summary$gm_file$total_ltrs_nucl_freq, genome.summary$gm_file$genome_size_nucl_mbp, method = cor.method)
        
        if (type == "n_ltrs")
            res <-
                ggplot2::ggplot(genome.summary$gm_file,
                                ggplot2::aes(x = n_ltrs,
                                             y = genome_size_nucl_mbp))
        
        if (type == "n_ltrs_freq")
            res <-
                ggplot2::ggplot(genome.summary$gm_file,
                                ggplot2::aes(x = n_ltrs_freq,
                                             y = genome_size_nucl_mbp))
        
        if (type == "total_ltrs_nucl_mbp")
            res <-
                ggplot2::ggplot(
                    genome.summary$gm_file,
                    ggplot2::aes(x = total_ltrs_nucl_mbp,
                                 y = genome_size_nucl_mbp)
                )
        if (type == "total_ltrs_nucl_freq")
            res <-
                ggplot2::ggplot(
                    genome.summary$gm_file,
                    ggplot2::aes(x = total_ltrs_nucl_freq * 100,
                                 y = genome_size_nucl_mbp)
                )
        
        res <- res + ggplot2::geom_point(size = 5, colour = colour) +
            ggplot2::theme_minimal() +
            ggplot2::labs(
                x = xlab,
                y = ylab,
                title = paste0(
                    main,
                    " [ Corr ( ",
                    cor.method,
                    " ) = ",
                    round(cor.value, digits = 2),
                    " ]"
                )
            ) +
            ggplot2::theme(legend.text = ggplot2::element_text(size = text.size)) +
            ggplot2::theme(
                axis.title  = ggplot2::element_text(size = text.size, face = "bold"),
                axis.text.y = ggplot2::element_text(size = text.size, face = "bold"),
                axis.text.x = ggplot2::element_text(size = text.size, face = "bold"),
                panel.background = ggplot2::element_blank(),
                plot.title = ggplot2::element_text(
                    size = text.size,
                    colour = "black",
                    face = "bold"
                )
            )
        
        if (label.organism) {
            if (!arrow_lab) {
                res <- res + ggplot2::geom_text(
                    ggplot2::aes(label = organism),
                    hjust = 0,
                    vjust = 0,
                    size = label.size,
                    check_overlap = check.overlap,
                    fontface = 'bold'
                )
            }
            
            if (arrow_lab) {
                res <-
                    res + ggrepel::geom_text_repel(ggplot2::aes(label = organism),
                                                   size = label.size,
                                                   fontface = 'bold')
            }
        }
        
        res <- res +
            ggplot2::scale_y_continuous(breaks = scales::pretty_breaks(n = 6)) +
            ggplot2::scale_x_continuous(breaks = scales::pretty_breaks(n = 6))
        
        if (!is.null(smooth.method)) {
            res <-
                res + ggplot2::geom_smooth(method = smooth.method,
                                           se = se,
                                           alpha = alpha,
                                           colour = "black",
                                           size = 2)
        }
        
        print(res)
    }


