#' @title Visualize the Superfamily distribution of predicted LTR retrotransposons
#' @details Plot the Superfamily distribution of predicted LTR retrotransposons of
#' annotations generated via Dfam or Repbase query. 
#' @param LTRpred.tbl \code{data.frame} returned by \code{\link{LTRpred}}.
#' @param xlab label of the x-axis.
#' @param ylab label of the y-axis.
#' @param main title text.
#' @param legend.title text of the legend title.
#' @param annotation which database has been used to generate annotation queries when running \code{\link{LTRpred}}? 
#' Either \code{annotation = "Dfam"} or \code{annotation = "Repbase"}.
#' @author Hajk-Georg Drost
#' @examples 
#' # example prediction file generated by LTRpred 
#' pred.file <- system.file("Athaliana_TAIR10_chr_all_LTRpred_DataSheet.csv", package = "LTRpred")
#' read LTRpred generated prediction file (data sheet)
#' pred <- read.ltrpred(pred.file)
#' 
#' # visualize superfamily distribution
#' PlotFamily(pred)
#' @seealso \code{\link{LTRpred}}, \code{\link{read.ltrpred}}, \code{\link{dfam.query}}, \code{\link{repbase.query}}
#' @export

PlotFamily <- function(LTRpred.tbl,
                       xlab = "\nAnnotated Superfamily Name",
                       ylab = "Predicted LTR retrotransposons (count)\n",
                       main = "Superfamily distribution of predicted LTR retrotransposons",
                       legend.title = "Superfamily",
                       annotation = "Dfam") {
    
    if (!is.element(annotation,c("Dfam","Repbase")))
        stop("Please choose either 'Dfam' or 'Repbase' as annotation specification.")
    
    if (annotation == "Dfam") {
        p <-
            ggplot2::ggplot(LTRpred.tbl, ggplot2::aes(x = dfam_target_name, fill = factor(dfam_target_name))) + 
            ggplot2::geom_bar() + 
            ggplot2::labs(x = xlab, y = ylab, title = main) +
            ggplot2::scale_fill_discrete(name = legend.title) +
            ggplot2::theme_minimal() +
            ggplot2::theme(
                title            = ggplot2::element_text(size = 18, face = "bold"),
                legend.title     = ggplot2::element_text(size = 18, face = "bold"),
                legend.text      = ggplot2::element_text(size = 18, face = "bold"),
                axis.title       = ggplot2::element_text(size = 18, face = "bold"),
                axis.text.y      = ggplot2::element_text(size = 18, face = "bold"),
                axis.text.x      = ggplot2::element_text(size = 18, face = "bold"),
                panel.background = ggplot2::element_blank(),
                strip.text.x     = ggplot2::element_text(
                    size           = 18,
                    colour         = "black",
                    face           = "bold"
                ),
                panel.grid.major = ggplot2::element_line(color = "gray50", size = 0.5),
                panel.grid.major.x = ggplot2::element_blank()
            ) +
            ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 1,hjust = 1))
        
        return(p)   
    }
    
    if (annotation == "Repbase") {
        stop("Repbase annotation has not been implemented yet.")
    }
}
