#' @title Plot the LTR width distribution
#' @description Function to visualize the correlation between LTR transposon age
#' (measured in LTR similarity) and the width of the corresponding LTR element.
#' @param LTRpred.tbl the \code{\link{data.frame}} generated by \code{\link{LTRpred}}.
#' @param type type of visualization: either \code{type = "boxplot"} or \code{type = "violin"}.
#' @param similarity.bin resolution of similarity binning. E.g. binning 98\%-100\% into 0.5\% intervals would be \code{similarity.bin = 0.5}.
#' @param min.sim minimum similarity between LTRs that can shall be considered for visualization.
#' @author Hajk-Georg Drost 
#' @examples 
#' \dontrun{
#' # run LTRpred for A. thaliana
#' Ath.Pred <- LTRpred()
#' # visualize the collelation between LTR transposon age and width
#' # of predicted  A. thaliana LTR element
#' PlotLTRWidthDistribution(Ath.Pred)
#' }
#' 
#' @export

PlotLTRWidthDistribution <- function(LTRpred.tbl, 
                                     type           = "boxplot", 
                                     similarity.bin = NULL, 
                                     min.sim        = NULL){
    
    if (!is.element(type, c("boxplot","violin")))
        stop ("Please choose either type = 'boxplot' or type = 'violin'.")
    
    ltr_order <- width <- similarity <- ltr_similarity <- NULL
  
    if (is.null(similarity.bin) & is.null (min.sim)){
        
        #max.width <- max(LTRpred.tbl$ltr.retrotransposon[ , "ltr_similarity"])
        if (type == "boxplot"){
            
            res <- ggplot2::ggplot(LTRpred.tbl$ltr, ggplot2::aes(x = ltr_order , y = width, fill = similarity))  + ggplot2::geom_boxplot() + 
                ggplot2::facet_grid(. ~ similarity)  + ggplot2::labs(x = "\nLTR Position", y = "LTR length in bp\n") + ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 1,hjust = 1)) +
                ggplot2::theme(axis.text=ggplot2::element_text(size=18), axis.title=ggplot2::element_text(size=20,face="bold")) + ggplot2::geom_point(stat = "summary", fun.y = "mean", size = I(3), color = I("black")) + 
                ggplot2::geom_point(stat = "summary", fun.y = "mean", size = I(2.2), color = I("orange"))
            
#             res <- ggplot2::ggplot(LTRpred.tbl$ltr, ggplot2::aes(x = similarity , y = width, fill = similarity)) + ggplot2::geom_boxplot() + ggplot2::labs(x = "\nLTR % Similarity", y = "LTR length in bp\n") + 
#                 ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 1,hjust = 1)) +
#                 ggplot2::theme(axis.text=ggplot2::element_text(size=18), axis.title=ggplot2::element_text(size=20,face="bold")) 
            #+ ggplot2::scale_y_continuous(breaks = seq(0,ceiling(max.width),ceiling(max.width) * 0.1))
            
        }
        
        else if (type == "violin"){
            
            
            res <- ggplot2::ggplot(LTRpred.tbl$ltr, ggplot2::aes(x = ltr_order , y = width, fill = similarity))  + ggplot2::geom_violin() + 
                ggplot2::facet_grid(. ~ similarity)  + ggplot2::labs(x = "\nLTR Position", y = "LTR length in bp\n") + ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 1,hjust = 1)) +
                ggplot2::theme(axis.text=ggplot2::element_text(size=18), axis.title=ggplot2::element_text(size=20,face="bold")) + ggplot2::geom_point(stat = "summary", fun.y = "mean", size = I(3), color = I("black")) + 
                ggplot2::geom_point(stat = "summary", fun.y = "mean", size = I(2.2), color = I("orange"))
            
            
#             res <- ggplot2::ggplot(LTRpred.tbl$ltr, ggplot2::aes(x = similarity , y = width, fill = similarity)) + ggplot2::geom_violin(trim = FALSE) + ggplot2::labs(x = "\nLTR % Similarity", y = "LTR length in bp\n") + 
#                 ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 1,hjust = 1)) +
#                 ggplot2::theme(axis.text=ggplot2::element_text(size=18), axis.title=ggplot2::element_text(size=20,face="bold"))
            #+ ggplot2::scale_y_continuous(breaks = seq(0,ceiling(max.width),ceiling(max.width) * 0.1))
            
        }
    }
    
    if (!is.null(similarity.bin) & !is.null (min.sim)){
        
      LTRpred.tbl$ltr <- dplyr::filter(LTRpred.tbl$ltr, ltr_similarity >= min.sim)
      LTRpred.tbl$ltr <- dplyr::mutate(LTRpred.tbl$ltr, 
                                                                    similarity = cut(ltr_similarity,
                                                                                     rev(seq(100,min.sim,-similarity.bin)),
                                                                                     include.lowest = TRUE,
                                                                                     right          = TRUE))
        
        #max.width <- max(LTRpred.tbl$ltr.retrotransposon[ , "ltr_similarity"])
        if (type == "boxplot"){
            
            res <- ggplot2::ggplot(LTRpred.tbl$ltr, ggplot2::aes(x = ltr_order , y = width, fill = similarity))  + ggplot2::geom_boxplot() + 
                ggplot2::facet_grid(. ~ similarity)  + ggplot2::labs(x = "\nLTR Position", y = "LTR length in bp\n") + ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 1,hjust = 1)) +
                ggplot2::theme(axis.text=ggplot2::element_text(size=18), axis.title=ggplot2::element_text(size=20,face="bold")) + ggplot2::geom_point(stat = "summary", fun.y = "mean", size = I(3), color = I("black")) + 
                ggplot2::geom_point(stat = "summary", fun.y = "mean", size = I(2.2), color = I("orange"))
            
#             res <- ggplot2::ggplot(LTRpred.tbl$ltr,ltr_similarity, ggplot2::aes(x = similarity , y = width, fill = similarity)) + ggplot2::geom_boxplot() + ggplot2::labs(x = "\nLTR % Similarity", y = "LTR length in bp\n") + 
#                 ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 1,hjust = 1)) +
#                 ggplot2::theme(axis.text=ggplot2::element_text(size=18), axis.title=ggplot2::element_text(size=20,face="bold")) 
            #+ ggplot2::scale_y_continuous(breaks = seq(0,ceiling(max.width),ceiling(max.width) * 0.1))
            
        }
        
        else if (type == "violin"){
            
            res <- ggplot2::ggplot(LTRpred.tbl$ltr, ggplot2::aes(x = ltr_order , y = width, fill = similarity))  + ggplot2::geom_violin() + 
                ggplot2::facet_grid(. ~ similarity)  + ggplot2::labs(x = "\nLTR Position", y = "LTR length in bp\n") + ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 1,hjust = 1)) +
                ggplot2::theme(axis.text=ggplot2::element_text(size=18), axis.title=ggplot2::element_text(size=20,face="bold")) + ggplot2::geom_point(stat = "summary", fun.y = "mean", size = I(3), color = I("black")) + 
                ggplot2::geom_point(stat = "summary", fun.y = "mean", size = I(2.2), color = I("orange"))
            
            
#             res <- ggplot2::ggplot(LTRpred.tbl$ltr, ggplot2::aes(x = similarity , y = width, fill = similarity)) + ggplot2::geom_violin(trim = FALSE) + ggplot2::labs(x = "\nLTR % Similarity", y = "LTR length in bp\n") + 
#                 ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 1,hjust = 1)) +
#                 ggplot2::theme(axis.text=ggplot2::element_text(size=18), axis.title=ggplot2::element_text(size=20,face="bold"))
            #+ ggplot2::scale_y_continuous(breaks = seq(0,ceiling(max.width),ceiling(max.width) * 0.1))
            
        }
    }
    
    return(res)
}


