#' @title Plot the median cluster copy number distribution of putative LTR transposons for kingdoms of life
#' @description Visualize the correlation between LTR transposon age
#' (measured in LTR similarity) and the median cluster copy number of the corresponding LTR retrotransposon (the complete sequence) 
#' or the width of the left LTR element for each species stored in the input \code{data}.
#' @param data the \code{\link{data.frame}} generated by \code{\link[LTRpred]{LTRpred}}.
#' @param element.type which width shall be visualized. Full retrotransposon width or only LTR element width: 
#' choose \code{element.type = "full_retrotransposon"} or \code{element.type = "ltr_element"}. 
#' In case \code{element.type = "ltr_element"} is chosen then the width of the left LTR element is 
#' used to visualize width vs. seq. similarity between the LTRs.
#' @param plot.type type of visualization: either \code{plot.type = "boxplot"} or \code{plot.type = "violin"}.
#' @param similarity.bin resolution of similarity binning. E.g. binning 98\%-100\% into 0.5\% intervals would be \code{similarity.bin = 0.5}. 
#' @param min.sim minimum similarity between LTRs that can shall be considered for visualization.
#' @param quality.filter shall false positives be filtered out as much as possible or not. See Description for details.
#' @param n.orfs minimum number of ORFs detected in the putative LTR transposon.
#' @param include.unique shall unique elements be visualized together with the clusters?
#' @param xlab label of x-axis.
#' @param ylab label of y-axis.
#' @param main title label.
#' @param legend.title title of legend.
#' @param y.ticks number of ticks at the y-axis. Default is \code{y.ticks = 10}.
#' @author Hajk-Georg Drost
#' @details This function visualizes the correlation between LTR transposon age
#' (measured in LTR similarity) and the cluster copy number of the corresponding LTR retrotransposon (the complete sequence) or the width of the left LTR element. Using this visualization approach, different classes of LTR retrotransposons can be detected due to their width and age correlation.
#' @export

plot_copynumber_kingdom <- function(data,
                                  element.type   = "full_retrotransposon",
                                  plot.type      = "boxplot", 
                                  similarity.bin = 2, 
                                  min.sim        = 70,
                                  quality.filter = FALSE,
                                  n.orfs         = 0,
                                  include.unique = FALSE,
                                  xlab           = "LTR % Similarity",
                                  ylab           = "Median Copy Number",
                                  main           = "",
                                  legend.title   = "Similarity between LTRs",
                                  y.ticks        = 10){
    
    if (!is.element(plot.type, c("boxplot","violin")))
        stop("Please choose either type = 'boxplot' or type = 'violin'.", call. = FALSE)
    
    if (!is.element(element.type, c("full_retrotransposon", "ltr_element")))
        stop("Please choose either element.type = 'full_retrotransposon' or element.type = 'ltr_element'.", call. = FALSE)
    
    similarity <- Clust_cn <- cn_3ltr <- ltr_similarity <- NULL
    kingdom <- species <- Clust_Cluster <- median_cn <- NULL
    
    if (quality.filter)
        data <- LTRpred::quality.filter(data, sim = min.sim, n.orfs = n.orfs)
    if (!quality.filter) {
        message("No quality filter has been applied.")
    }
    
    if (!is.null(similarity.bin) & !is.null(min.sim)) {
        
        data <- dplyr::filter(data, ltr_similarity >= min.sim)
        data <- dplyr::mutate(data,
                              similarity = cut(
                                  ltr_similarity,
                                  rev(seq(100, min.sim, -similarity.bin)),
                                  include.lowest = TRUE,
                                  right          = TRUE
                              ))
    }
    
    if (include.unique) {
        # group by species and similarity and compute the median LTR/Retrotransposon width for each species
        pred_median_sim_retrotrans <- dplyr::summarise(dplyr::group_by(data, kingdom, species, similarity), median_cn = stats::median(Clust_cn))
        pred_median_sim_ltr_only <- dplyr::summarise(dplyr::group_by(data, kingdom, species, similarity), median_cn = stats::median(cn_3ltr))
    }
    
    if (!include.unique) {
        # group by species and similarity and compute the median LTR/Retrotransposon width for each species
        pred_median_sim_retrotrans <- dplyr::summarise(dplyr::group_by(dplyr::filter(data, Clust_Cluster != "unique"), kingdom, species, similarity), median_cn = stats::median(Clust_cn))
        pred_median_sim_ltr_only <- dplyr::summarise(dplyr::group_by(dplyr::filter(data, Clust_Cluster != "unique"), kingdom, species, similarity), median_cn = stats::median(cn_3ltr))
    }
    
    #max.width <- max(data$ltr.retrotransposon[ , "ltr_similarity"])
    if (element.type == "full_retrotransposon") {
        res <-
            ggplot2::ggplot(pred_median_sim_retrotrans, ggplot2::aes(similarity, median_cn))
    }
    
    if (element.type == "ltr_element") {
        res <-
            ggplot2::ggplot(pred_median_sim_ltr_only, ggplot2::aes(similarity, median_cn))
    }
    
    if (plot.type == "boxplot") {
        res <-
            res + ggplot2::facet_wrap(~kingdom) + ggplot2::geom_boxplot( size = 1.5) + 
            ggplot2::geom_point(ggplot2::aes(colour = kingdom)) + 
            ggplot2::geom_jitter(ggplot2::aes(colour = kingdom), position = ggplot2::position_jitter(0.2))
    }
    
    if (plot.type == "violin") {
        res <-
            res + ggplot2::facet_wrap(~kingdom) + ggplot2::geom_violin( size = 1.5) + 
            ggplot2::geom_point(ggplot2::aes(colour = kingdom)) + 
            ggplot2::geom_jitter(ggplot2::aes(colour = kingdom), position = ggplot2::position_jitter(0.2))
    }
    
    res <-
        res + ggplot2::labs(x = xlab, y = ylab, title = main) +
        ggplot2::scale_fill_discrete(name = legend.title) +
        ggplot2::theme(
            title            = ggplot2::element_text(size = 18, face = "bold"),
            legend.title     = ggplot2::element_text(size = 18, face = "bold"),
            legend.text      = ggplot2::element_text(size = 18, face = "bold"),
            axis.title       = ggplot2::element_text(size = 18, face = "bold"),
            axis.text.y      = ggplot2::element_text(size = 18, face = "bold"),
            axis.text.x      = ggplot2::element_text(size = 18, face = "bold"),
            panel.background = ggplot2::element_blank(),
            strip.text.x     = ggplot2::element_text(
                size           = 18,
                colour         = "black",
                face           = "bold"
            ),
            panel.grid.major = ggplot2::element_line(color = "gray50", size = 0.5),
            panel.grid.major.x = ggplot2::element_blank()
        ) +
        ggplot2::theme(axis.text.x = ggplot2::element_text(
            angle = 90,
            vjust = 1,
            hjust = 1
        )) +
        ggplot2::scale_y_continuous(breaks = scales::pretty_breaks(n = y.ticks))
    
    return(res)
}
