#' @title Visualize the Protein Domain distribution of predicted LTR retrotransposons
#' @description Plot the Superfamily distribution of predicted LTR retrotransposons of
#' annotations generated via Dfam or Repbase query. 
#' @param LTRpred.tbl \code{data.frame} returned by \code{\link{LTRpred}}.
#' @param xlab label of the x-axis.
#' @param ylab label of the y-axis.
#' @param main title text.
#' @param legend.title text of the legend title.
#' Either \code{annotation = "Dfam"} or \code{annotation = "Repbase"}.
#' @author Hajk-Georg Drost
#' @examples 
#' # example prediction file generated by LTRpred 
#' pred.file <- system.file("Athaliana_TAIR10_chr_all_LTRpred_DataSheet.csv", package = "LTRpred")
#' read LTRpred generated prediction file (data sheet)
#' pred <- read.ltrpred(pred.file)
#' 
#' # visualize superfamily distribution
#' PlotFamily(pred)
#' @seealso \code{\link{LTRpred}}, \code{\link{read.ltrpred}}, \code{\link{dfam.query}}, \code{\link{repbase.query}}
#' @export

PlotProteinDomain <- function(LTRpred.tbl,
                       xlab = "\nDetected Protein Domains",
                       ylab = "Predicted LTR retrotransposons (count)\n",
                       main = "Protein Domain distribution of predicted LTR retrotransposons",
                       legend.title = "Protein Domains") {

        
        protein_domain <- NULL
         
        LTRpred.tbl <- dplyr::mutate(LTRpred.tbl, protein_domain = ifelse(is.na(protein_domain),"none",protein_domain))
        p <-
            ggplot2::ggplot(LTRpred.tbl, ggplot2::aes(x = protein_domain, fill = factor(protein_domain))) + 
            ggplot2::geom_bar() + 
            ggplot2::labs(x = xlab, y = ylab, title = main) +
            ggplot2::scale_fill_discrete(name = legend.title) +
            ggplot2::theme_minimal() +
            ggplot2::theme(
                title            = ggplot2::element_text(size = 18, face = "bold"),
                legend.title     = ggplot2::element_text(size = 18, face = "bold"),
                legend.text      = ggplot2::element_text(size = 18, face = "bold"),
                axis.title       = ggplot2::element_text(size = 18, face = "bold"),
                axis.text.y      = ggplot2::element_text(size = 18, face = "bold"),
                axis.text.x      = ggplot2::element_text(size = 18, face = "bold"),
                panel.background = ggplot2::element_blank(),
                strip.text.x     = ggplot2::element_text(
                    size           = 18,
                    colour         = "black",
                    face           = "bold"
                ),
                panel.grid.major = ggplot2::element_line(color = "gray50", size = 0.5),
                panel.grid.major.x = ggplot2::element_blank()
            ) +
            ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 1,hjust = 1))
        
        return(p)   
}
