#' @title Plot the age distribution of predicted LTR transposons
#' @description 
#' This function visualizes the age distribution of
#' predicted LTR transposons generated with \code{\link{LTRpred}}.
#' 
#' The age pf LTR transposons is defined by the sequence similarity of their
#' LTRs. Evolutionary young (recent) LTR transposons tend to have very similar
#' LTRs (up to 100\% sequence similarity), whereas evolutionary older LTR transposons
#' tend to have less similar LTRs.
#' @param LTRpred.tbl the \code{\link{data.frame}} generated by \code{\link{LTRpred}}.
#' @param similarity.bin resolution of similarity binning. E.g. binning 98\%-100\% into 0.5\% intervals would be \code{similarity.bin = 0.5}.
#' @param min.sim 
#' @author Hajk-Georg Drost
#' @details This way of visualizing the age distribution of LTR transposons
#' allows users to examine the rate of recent transposition events in extant organisms. 
#' 
#' @examples 
#' \dontrun{
#' # run LTRpred for A. thaliana
#' Ath.Pred <- LTRpred()
#' # visualize the age distribution of predicted  A. thaliana LTR transposons
#' PlotLTRAgeDistribution(Ath.Pred)
#' }
#' @seealso \code{\link{LTRpred}}, \code{\link{LTRharvest}}, \code{\link{LTRdigest}},
#' \code{\link{PlotLTRAgeDistribution}}, \code{\link{PlotLTRTransposonWidthDistribution}},
#' \code{\link{PlotLTRWidthDistribution}}, \code{\link{PlotRanges}}
#' @export

PlotLTRAgeDistribution <- function(LTRpred.tbl, similarity.bin = NULL, min.sim = NULL){
    
    similarity <- ltr_similarity <- NULL
    
    if (is.null(similarity.bin) & is.null (min.sim)){
        
        res <- ggplot2::ggplot(LTRpred.tbl, ggplot2::aes(x = similarity), order = FALSE) +
            ggplot2::geom_bar(stat = "count", fill = "turquoise4") + ggplot2::labs(x = "LTR % Similarity", y = "Frequency") +
            ggplot2::theme_minimal() + ggplot2::theme(axis.title=ggplot2::element_text(size=14,face="bold"),axis.text.y = ggplot2::element_text(size=14,face="bold"),axis.text.x = ggplot2::element_text(size=14,face="bold"),
                                                      panel.background = ggplot2::element_blank(), plot.title = ggplot2::element_text(size = 20, colour = "black", face = "bold"))
        
    }
    
    if (!is.null(similarity.bin) & !is.null (min.sim)){
        
        LTRpred.tbl <- dplyr::filter(LTRpred.tbl, ltr_similarity >= min.sim)
        LTRpred.tbl <- dplyr::mutate(LTRpred.tbl, 
                                                    similarity = cut(ltr_similarity,
                                                                     rev(seq(100,min.sim,-similarity.bin)),
                                                                     include.lowest = TRUE,
                                                                     right          = TRUE))
        
    
        res <- ggplot2::ggplot(LTRpred.tbl, ggplot2::aes(x = similarity), order = FALSE) +
        ggplot2::geom_bar(stat = "count", fill = "turquoise4") + ggplot2::labs(x = "LTR % Similarity", y = "Frequency") +
        ggplot2::theme_minimal() + ggplot2::theme(axis.title=ggplot2::element_text(size=14,face="bold"),axis.text.y = ggplot2::element_text(size=14,face="bold"),axis.text.x = ggplot2::element_text(size=14,face="bold"),
        panel.background = ggplot2::element_blank(), plot.title = ggplot2::element_text(size = 20, colour = "black", face = "bold"))
    }
    
    return(res)
}