#' @title Plot the location of putative LTR transposons along the chromosomes
#' @description Visualization of the location of putative LTR transposons along chromosomes.
#' @param data the \code{\link{data.frame}} generated by \code{\link{LTRpred}}.
#' @author Hajk-Georg Drost
#' @export

plotLTRRange <- function(data){
  
    chromosome <- NULL  
    chromosomes <- names(table(data[ , "chromosome"]))
    graphics::par(mfrow = grDevices::n2mfrow(length(chromosomes)))
    sapply(chromosomes, function(chr){
        
        ltr.ranges <- dplyr::filter(data, chromosome == chr)
        plotRanges(IRanges::IRanges(ltr.ranges[ , "start"],ltr.ranges[ , "end"]), main = chr)
    })
    
}

PlotRangesLTRharvestPrediction2 <- function(data){
    
    chromosome <- NULL
    chromosomes <- names(table(data$ltr.retrotransposon[ , "chromosome"]))
#     par(mfrow = n2mfrow(length(chromosomes)))
#     sapply(chromosomes, function(chr){
#         
#         ltr.ranges <- dplyr::filter(data$ltr.retrotransposon, chromosome == chr)
#         ggbio::autoplot(IRanges::IRanges(ltr.ranges[ , "start"],ltr.ranges[ , "end"]), main = chr, geom = "segment")
#     })
#     
    
    ltr.ranges <- dplyr::filter(data$ltr.retrotransposon, chromosome == chromosomes[1])
    ggbio::autoplot(IRanges::IRanges(ltr.ranges[ , "start"],ltr.ranges[ , "end"]), main = chromosomes[1], geom = "arrowrect")
}
