#' @title Plot the location of putative LTR transposons along the chromosomes
#' @description Visualization of the location of putative LTR transposons along chromosomes.
#' @param LTRpred.tbl the \code{\link{data.frame}} generated by \code{\link{LTRpred}}.
#' @author Hajk-Georg Drost
#' @export

PlotLTRRange <- function(LTRpred.tbl){
    
    chromosome <- NULL
    chromosomes <- names(table(LTRpred.tbl[ , "chromosome"]))
    par(mfrow = grDevices::n2mfrow(length(chromosomes)))
    sapply(chromosomes, function(chr){
        
        ltr.ranges <- dplyr::filter(LTRpred.tbl, chromosome == chr)
        PlotRanges(IRanges::IRanges(ltr.ranges[ , "start"],ltr.ranges[ , "end"]), main = chr)
    })
    
}

PlotRangesLTRharvestPrediction2 <- function(LTRpred.tbl){
    
    chromosome <- NULL
    chromosomes <- names(table(LTRpred.tbl$ltr.retrotransposon[ , "chromosome"]))
#     par(mfrow = n2mfrow(length(chromosomes)))
#     sapply(chromosomes, function(chr){
#         
#         ltr.ranges <- dplyr::filter(LTRpred.tbl$ltr.retrotransposon, chromosome == chr)
#         ggbio::autoplot(IRanges::IRanges(ltr.ranges[ , "start"],ltr.ranges[ , "end"]), main = chr, geom = "segment")
#     })
#     
    
    ltr.ranges <- dplyr::filter(LTRpred.tbl$ltr.retrotransposon, chromosome == chromosomes[1])
    ggbio::autoplot(IRanges::IRanges(ltr.ranges[ , "start"],ltr.ranges[ , "end"]), main = chromosomes[1], geom = "arrowrect")
}
