#' @title Format LTR prediction data to GFF3 file format
#' @description This function formats the LTR prediction \code{\link{data.frame}}
#' generated by \code{\link{LTRharvest}}, \code{\link{LTRdigest}}, or \code{\link{LTRpred}}
#' to a \code{\link{data.frame}} in \code{GFF3} file format.
#' @param LTR.data the LTR prediction \code{\link{data.frame}}
#' generated by \code{\link{LTRharvest}}, \code{\link{LTRdigest}}, or \code{\link{LTRpred}}.
#' @author Hajk-Georg Drost
#' @details 
#' The GFF3 file format is defined by: chromosome; start; end; name; columns.
#' @examples 
#' gff.file <- system.file("TAIR10_chr_all_LTRdigestPrediction.gff",
#'                         package = "LTRpred")
#' tabout.file <- system.file("TAIR10_chr_all-ltrdigest_tabout.csv"
#'                            ,package = "LTRpred")
#' LTRfile <- read.prediction(gff.file,tabout.file, program = "LTRdigest")
#' 
#' # generate GFF file
#' gff.example <- pred2gff(LTRfile$ltr.retrotransposon)
#' head(gff.example)
#' 
#' # write GFF file to hard drive
#' write.table(gff.example,"test.gff", quote = FALSE, col.names = TRUE, row.names = FALSE)
#' @references http://www.ensembl.org/info/website/upload/gff.html
#' @export
pred2gff <- function(LTR.data){
  
  chromosome <- ltr_similarity <- element_length <- attribute <- NULL
  
  res <- dplyr::data_frame(seqname   = LTR.data$ID, 
                           source    = LTR.data$pred_tool, 
                           feature   = LTR.data$annotation,
                           start     = LTR.data$start,
                           end       = LTR.data$end,
                           score     = LTR.data$score,
                           strand    = LTR.data$strand,
                           frame     = LTR.data$frame, 
                           attribute = unlist(dplyr::select(dplyr::mutate(LTR.data, attribute = paste0("Chr=",chromosome,";","ltr.sim=",ltr_similarity,";","element_length=",element_length)),attribute)))
  
  return(res)
}


