#' @title Format LTR prediction data to chromoMap package annotation file format
#' @description This function formats the LTR prediction \code{\link{data.frame}}
#' generated by \code{\link{LTRpred}} to a \code{chromoMap} package annotation file.
#' @param LTR.data the LTR prediction \code{\link{data.frame}} generated by \code{\link{LTRpred}}.
#' @param output filename of the output chromoMap file.
#' @author Hajk-Georg Drost
#' @details 
#' The chromoMap file format is defined by: element_name; chromosome_name; element_start; element_end; data.
#' @references https://cran.r-project.org/web/packages/chromoMap/vignettes/chromoMap.html
#' @export
pred2chromoMap <- function(LTR.data, output = "output"){
  
  res <- dplyr::data_frame(element_name = LTR.data$ID,
                           chromosome = LTR.data$chromosome, 
                           start      = LTR.data$start, 
                           end        = LTR.data$end,
                           data       = LTR.data$orfs)
  
  utils::write.table(res,output, sep = "\t", quote = FALSE, col.names = FALSE, row.names = FALSE)
}


