#' @title Try to eliminate false positive LTRpred predictions by filter strategy
#' @description This function takes an \code{\link{LTRpred}} output table as input
#' and eliminates false positive predictions.
#' @param pred \code{LTRpred.tbl} generated with \code{\link{LTRpred}}
#' @param sim LTR similarity threshold. Only putative LTR transposons that fulfill this 
#' LTR similarity threshold will be retained.
#' @param n.orfs minimum number of ORFs detected in the putative LTR transposon.
#' @author Hajk-Georg Drost
#' @examples 
#' # example prediction file generated by LTRpred 
#' pred.file <- system.file("Athaliana_TAIR10_chr_all_LTRpred_DataSheet.csv", package = "LTRpred")
#' # read LTRpred generated prediction file (data sheet)
#' pred <- read.ltrpred(pred.file)
#' # apply quality filter
#' pred <- quality.filter(pred, sim = 70, n.orfs = 1)
#' @return A quality filtered \code{LTRpred.tbl}.
#' @seealso \code{\link{LTRpred}}, \code{\link{read.ltrpred}} 
#' @export 

quality.filter <- function(pred, sim, n.orfs){
    # try to reduce false positives by filtering for PBS and ORFs
    cat("\n")
    filtered.res <- dplyr::filter(pred,
                          ltr_similarity >= sim,
                          (!is.na(PBS_start)) |
                              (!is.na(protein_domain)),
                          orfs >= n.orfs)
    cat("The LTRpred prediction table has been filtered (default) to remove potential false positives. Predicted LTRs must have an PBS or Protein Domain and must fulfill thresholds: sim = ",sim,"%; #orfs = ",n.orfs,".")
    cat("\n")
    return(filtered.res)   
}
