#' @title Import the data sheet file generated by \code{LTRpred}
#' @description The \code{*_LTRpred_DataSheet.csv} file generated by \code{\link{LTRpred}} stores the featured of all predicted LTR transposons in a table. This function
#' imports this table.
#' @param data.sheet path to the \code{*_LTRpred_DataSheet.csv} file.
#' @author Hajk-Georg Drost 
#' @export
   
read.ltrpred <- function(data.sheet){
   if (file.info(data.sheet)$size == 0 || is.na(file.info(data.sheet)$size == 0)){
     cat("File ",data.sheet, " is empty and therefore is not being processed.")
     cat("\n")
     cat("\n")
     return (NULL)
   }
  pred <- readr::read_delim(data.sheet, delim = ";")
  return (pred)
}