#' @title Import information sheet returned by LTRdigest
#' @description This function
#' @param tabout.file path to the tabout.csv file generated by the \code{\link{LTRdigest}} function.
#' @author Hajk-Georg Drost
#' @export

read.tabout <- function(tabout.file){
    
    LTRdigest.tabout.header <- readr::read_lines(tabout.file, n_max = 1)
    
    LTRdigest.tabout.header.names <- stringr::str_replace_all(unlist(stringr::str_split(LTRdigest.tabout.header,"\t"))," ","_")
    LTRdigest.tabout <- readr::read_tsv(tabout.file, skip = 1, col_names = FALSE)
    colnames(LTRdigest.tabout) <- c(LTRdigest.tabout.header.names,"protein_domain")
    
    return (LTRdigest.tabout)
}